# Task 4.8: Grouping Data & Aggregating Variables

## Reusing the notebook I built during the Exercise, so that I have the Exercise's subset DF (ords_prods_merge) to compare with the same operations on the full DF (orders_products_merged).
## Please search for "Beginning TASK 4.8" to review this task submission.

## Standard prerequisites.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Starting with Exercise 4.7, import additional libraries I've discovered thanks to Lubov, especially the time library.
import time
import string
import random

In [3]:
# Set a PATH variable.

In [4]:
# Linux PATH - Sadly, my Linux system with 8GB of total RAM could not import the new df_ords_prior DataFrame.
# BUT, now I have moved again, to an AWS EC2 instance that should be able to handle this.

In [5]:
path = (r'~/careerfoundry/tasks/data-immersion/Achievement4/Instacart-Basket-Analysis')

In [6]:
# windoze PATH - The windoze laptop I bought for Excel and Tableau also has 16GB of RAM, so I migrated there.

In [7]:
## path = (r'C:\Users\emccc\OneDrive\Documents\CareerFoundry\Achievement-4\Instacart-Basket-Analysis')

# Read the orders_products_merged.pkl file into a new DataFrame, ords_prods_merge , per Exercise 4.8 instructions

In [8]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '02-Data', 'Prepared-Data', 'orders_products_merged.pkl'))

In [9]:
ords_prods_merge['prices'].max()

99999.0

## Create a subset called df of the first one million entries.

In [10]:
df = ords_prods_merge[:1000000]

In [11]:
df.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,customer_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,_merge2,price_range,price_range_loc,busiest_days,busiest_hours
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,0.0,10,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy

In [12]:
df.shape

(1000000, 20)

In [13]:
df.groupby('product_name')

In [14]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [15]:
df.groupby('department_id')['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

In [16]:
# Another way to write the above, only with "dot notation."
# The Exercise recommends, however, to use the method above, instead:
# "In general, stick to brackets when it comes to indexing!"

In [17]:
df.groupby('department_id').order_number.mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

In [18]:
# Multiple aggregations with one command.
# NB:  Per the Exercise, "the minimum orders will always be 1 and the maximum has been capped at 99 by the data engineers at Instacart."

In [19]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.447411   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.803851   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

In [20]:
# Create new column, 'max_order', in the ords_prods_merge Data Frame.

In [21]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['customer_id'])['order_number'].transform(np.max)

In [22]:
ords_prods_merge.shape

(32404859, 21)

In [23]:
ords_prods_merge.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,customer_id,order_number,orders_day_of_week,...,days_since_prior_order,add_to_cart_order,reordered,_merge,_merge2,price_range,price_range_loc,busiest_days,busiest_hours,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,...,3.0,5,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,32
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,...,20.0,1,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,32
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,...,6.0,20,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,5
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,...,0.0,10,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,3
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,...,9.0,11,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,3

In [24]:
ords_prods_merge.head(100)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,customer_id,order_number,orders_day_of_week,...,days_since_prior_order,add_to_cart_order,reordered,_merge,_merge2,price_range,price_range_loc,busiest_days,busiest_hours,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,...,3.0,5,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,32
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,...,20.0,1,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,32
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,...,6.0,20,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,5
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,...,0.0,10,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,3
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,...,9.0,11,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,...,23.0,5,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,10
96,0,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,...,30.0,1,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,23
97,0,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,...,2.0,8,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,26
98,0,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,...,0.0,2,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,43
99,0,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,...,3.0,6,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,21

In [25]:
pd.options.display.max_rows = None

In [26]:
ords_prods_merge.head(100)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,customer_id,order_number,orders_day_of_week,...,days_since_prior_order,add_to_cart_order,reordered,_merge,_merge2,price_range,price_range_loc,busiest_days,busiest_hours,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,...,3.0,5,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,32
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,...,20.0,1,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,32
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,...,6.0,20,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,5
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,...,0.0,10,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,3
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,...,9.0,11,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,3
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,...,26.0,7,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,26
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,...,30.0,2,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,9
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,...,30.0,1,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,12
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,...,19.0,1,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,20
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,...,15.0,2,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,20
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,...,0.0,1,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,10
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,...,7.0,1,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,43
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,...,7.0,3,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,43
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,...,12.0,4,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,43
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,...,2.0,8,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,13
15,0,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,...,6.0,18,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,13
16,0,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,...,10.0,12,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,13
17,0,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,...,7.0,10,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,28
18,0,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,...,6.0,9,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
19,0,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,...,14.0,9,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
20,0,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,...,8.0,7,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,28
21,0,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,...,6.0,6,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
22,0,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,...,28.0,6,1,both,both,Mid-range product,Mid-range product,Busiest days,Least busy hours,28
23,0,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,...,7.0,10,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
24,0,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,...,7.0,3,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
25,0,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,...,0.0,5,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
26,0,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,...,7.0,11,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
27,0,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,...,7.0,11,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
28,0,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,...,7.0,5,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
29,0,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,...,7.0,15,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
30,0,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,...,3.0,4,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,28
31,0,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,...,16.0,6,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,28
32,0,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,...,5.0,1,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
33,0,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,...,6.0,1,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,28
34,0,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,...,0.0,2,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,4
35,0,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,...,21.0,2,1,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,4
36,0,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,...,2.0,3,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,4
37,0,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,...,0.0,1,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,10
38,0,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,...,18.0,6,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,10
39,0,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,...,8.0,3,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,10
40,0,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,...,30.0,10,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,10
41,0,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,...,25.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,10
42,0,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,...,0.0,12,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,10
43,0,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,...,9.0,10,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,23
44,0,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,...,10.0,5,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,25
45,0,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,...,7.0,11,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,13
46,0,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,...,0.0,8,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,5
47,0,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,...,30.0,7,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,6
48,0,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,...,0.0,2,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,3
49,0,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,...,7.0,8,0,both,both,Mid-range product,Mid-range product,Busiest days,Busiest hours,42
50,0,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,...,7.0,2,1,both,both,Mid-range product,Mid-range product,Busiest days,Busiest hours,42
51,0,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,...,7.0,6,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,42
52,0,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,...,5.0,3,1,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,42
53,0,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,...,4.0,2,1,both,both,Mid-range product,Mid-range product,Busiest days,Busiest hours,42
54,0,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,...,8.0,1,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,40
55,0,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,...,30.0,2,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,9
56,0,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,...,0.0,9,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,4
57,0,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,...,29.0,1,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,4
58,0,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,...,12.0,7,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,14
59,0,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,...,0.0,11,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,6
60,0,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,...,4.0,6,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,8
61,0,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,...,5.0,5,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,21
62,0,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,...,5.0,6,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,21
63,0,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,...,13.0,3,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,21
64,0,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,...,10.0,2,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,31
65,0,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,...,6.0,1,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,31
66,0,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,...,9.0,1,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,31
67,0,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,...,6.0,2,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,31
68,0,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,...,8.0,2,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,31
69,0,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,...,1.0,13,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,99
70,0,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,...,7.0,2,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,36
71,0,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,...,21.0,2,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,9
72,0,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,...,30.0,2,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,5
73,0,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,...,30.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,5
74,0,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,...,0.0,11,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,5
75,0,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,...,30.0,3,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,23
76,0,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,...,8.0,2,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
77,0,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,...,7.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
78,0,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,...,14.0,2,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
79,0,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,...,28.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
80,0,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,...,16.0,4,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
81,0,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,...,1.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
82,0,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,...,14.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
83,0,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,...,7.0,2,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
84,0,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,...,8.0,1,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
85,0,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,...,16.0,7,1,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
86,0,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,...,8.0,16,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,23
87,0,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,...,14.0,5,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,11
88,0,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,...,0.0,2,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,5
89,0,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,...,8.0,8,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,22
90,0,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,...,14.0,15,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,21
91,0,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,...,14.0,9,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,21
92,0,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,...,10.0,1,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,36
93,0,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,...,14.0,4,1,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,36
94,0,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,...,4.0,2,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,36
95,0,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,...,23.0,5,0,both,both,Mid-range product,Mid-range product,Least busy days,Busiest hours,10
96,0,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,...,30.0,1,0,both,both,Mid-range product,Mid-range product,Busiest days,Regularly busy,23
97,0,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,...,2.0,8,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,26
98,0,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,...,0.0,2,0,both,both,Mid-range product,Mid-range product,Least busy days,Regularly busy,43
99,0,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,...,3.0,6,0,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,21

In [27]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [28]:
ords_prods_merge['loyalty_flag'].value_counts()

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

## So THIS is how we select individual columns for display.

In [29]:
ords_prods_merge[['customer_id', 'loyalty_flag', 'order_number']].head(60)

    customer_id      loyalty_flag  order_number
0           138  Regular customer            28
1           138  Regular customer            30
2           709      New customer             2
3           764      New customer             1
4           764      New customer             3
5           777  Regular customer            16
6           825      New customer             3
7           910  Regular customer            12
8          1052  Regular customer            10
9          1052  Regular customer            15
10         1379      New customer             1
11         1480    Loyal customer            36
12         1480    Loyal customer            38
13         1480    Loyal customer            39
14         1494  Regular customer             6
15         1494  Regular customer             7
16         1494  Regular customer             9
17         1540  Regular customer             4
18         1540  Regular customer             5
19         1540  Regular customer             6
20         1540  Regular customer             7
21         1540  Regular customer             8
22         1540  Regular customer             9
23         1540  Regular customer            14
24         1540  Regular customer            15
25         1540  Regular customer            18
26         1540  Regular customer            19
27         1540  Regular customer            20
28         1540  Regular customer            21
29         1540  Regular customer            22
30         1540  Regular customer            24
31         1540  Regular customer            25
32         1540  Regular customer            27
33         1540  Regular customer            28
34         1598      New customer             1
35         1598      New customer             2
36         1598      New customer             3
37         1647      New customer             1
38         1647      New customer             4
39         1647      New customer             6
40         1647      New customer             8
41         1647      New customer             9
42         2833      New customer             1
43         2850  Regular customer             7
44         2857  Regular customer            24
45         3010  Regular customer             5
46         3029      New customer             1
47         3395      New customer             4
48         3904      New customer             1
49         4006    Loyal customer             2
50         4006    Loyal customer             3
51         4006    Loyal customer             5
52         4006    Loyal customer             9
53         4006    Loyal customer            12
54         4122  Regular customer            11
55         4141      New customer             2
56         4343      New customer             1
57         4553      New customer             3
58         4845  Regular customer             6
59         6866      New customer             1

# Beginning TASK 4.8

## Step #1:  Create a new notebook for this task. Be sure to import the relevant libraries, along with your ords_prods_merge dataframe, which should include your newly derived columns from the previous Exercise.

### Done above.

## Step #2:  In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [30]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

## Step #3:  Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

### It's worth noting here that my subset of the first million entries contains entries for all twenty-one departments, which disagrees with the results in both the Exercise and at least one of the prior Approved submission examples.  I'm not sure why this is, but suspect some difference in ordering in either read_pickle or to_pickle, for my version of Python or pandas.

### We're looking to compare the results of an aggregate function on a full dataset with the results of the same function on an arbitrary subset:  almost anything could change, but since both results show 21 departments, I expect them to have different means.  Presumably, the means for the whole dataset will be somewhat higher (due to there being more orders and, hence, higher values for 'order_number')  At first glance, the means don't look very different, so I'll just display them side-by-side with a simple comparison function.

In [31]:
df_groupby =  pd.DataFrame(df.groupby('department_id').agg({'order_number': ['mean']}))

In [32]:
ords_prods_merge_groupby =  pd.DataFrame(ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']}))

In [33]:
df_temp_mean_compare = pd.concat([df_groupby, ords_prods_merge_groupby], axis = 1, keys = ['SUBSET', 'COMPLETE'])

In [34]:
df_temp_mean_compare

                    SUBSET     COMPLETE
              order_number order_number
                      mean         mean
department_id
1                15.577493    15.457838
2                17.320781    17.277920
3                16.084944    17.170395
4                17.530458    17.811403
5                14.763075    15.215751
6                16.658449    16.439806
7                17.031590    17.225802
8                15.076662    15.340650
9                15.447580    15.895474
10               18.681852    20.197148
11               15.447411    16.170638
12               14.327957    15.887671
13               16.548642    16.583536
14               16.960241    16.773669
15               16.121948    16.165037
16               17.803851    17.665606
17               15.593633    15.694469
18               19.674252    19.310397
19               16.899756    17.177343
20               16.255442    16.473447
21               25.535479    22.902379

In [35]:
df_temp_mean_compare['subset_mean_divided_by_complete_mean'] = (df_temp_mean_compare['SUBSET'] / df_temp_mean_compare['COMPLETE'])

In [36]:
df_temp_mean_compare

                    SUBSET     COMPLETE subset_mean_divided_by_complete_mean
              order_number order_number
                      mean         mean
department_id
1                15.577493    15.457838                             1.007741
2                17.320781    17.277920                             1.002481
3                16.084944    17.170395                             0.936784
4                17.530458    17.811403                             0.984227
5                14.763075    15.215751                             0.970250
6                16.658449    16.439806                             1.013300
7                17.031590    17.225802                             0.988726
8                15.076662    15.340650                             0.982792
9                15.447580    15.895474                             0.971823
10               18.681852    20.197148                             0.924975
11               15.447411    16.170638                             0.955275
12               14.327957    15.887671                             0.901829
13               16.548642    16.583536                             0.997896
14               16.960241    16.773669                             1.011123
15               16.121948    16.165037                             0.997334
16               17.803851    17.665606                             1.007826
17               15.593633    15.694469                             0.993575
18               19.674252    19.310397                             1.018842
19               16.899756    17.177343                             0.983840
20               16.255442    16.473447                             0.986766
21               25.535479    22.902379                             1.114971

### Hmmm, the means are much closer then I expected, and in some cases the mean for the subset is higher.
### Oh, of course:  since the data is in a different order (*not* ascending by order_number), the subset can contain entries for higher-numbered/later orders while omitting some lower-numbered/earlier ones.

In [37]:
ords_prods_merge['order_number'].head()

0    28
1    30
2     2
3     1
4     3
Name: order_number, dtype: int64

## Step #4:  Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

### If I understand correctly, we're just repeating the same operations for 'ords_prods_merge' as we did in the Exercise (above).  I will copy them here, but comment them out so that we don't create additional columns by mistake.

In [38]:
# Create new column, 'max_order', in the ords_prods_merge Data Frame.

In [39]:
## ords_prods_merge['max_order'] = ords_prods_merge.groupby(['customer_id'])['order_number'].transform(np.max)

In [40]:
## ords_prods_merge.shape

In [41]:
## ords_prods_merge.head()

In [42]:
## ords_prods_merge.head(100)

In [43]:
## pd.options.display.max_rows = None

In [44]:
## ords_prods_merge.head(100)

In [45]:
## ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
## ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
## ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [46]:
ords_prods_merge['loyalty_flag'].value_counts()

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

## So THIS is how we select individual columns for display.  I had wondered.

In [47]:
ords_prods_merge[['customer_id', 'loyalty_flag', 'order_number']].head(60)

    customer_id      loyalty_flag  order_number
0           138  Regular customer            28
1           138  Regular customer            30
2           709      New customer             2
3           764      New customer             1
4           764      New customer             3
5           777  Regular customer            16
6           825      New customer             3
7           910  Regular customer            12
8          1052  Regular customer            10
9          1052  Regular customer            15
10         1379      New customer             1
11         1480    Loyal customer            36
12         1480    Loyal customer            38
13         1480    Loyal customer            39
14         1494  Regular customer             6
15         1494  Regular customer             7
16         1494  Regular customer             9
17         1540  Regular customer             4
18         1540  Regular customer             5
19         1540  Regular customer             6
20         1540  Regular customer             7
21         1540  Regular customer             8
22         1540  Regular customer             9
23         1540  Regular customer            14
24         1540  Regular customer            15
25         1540  Regular customer            18
26         1540  Regular customer            19
27         1540  Regular customer            20
28         1540  Regular customer            21
29         1540  Regular customer            22
30         1540  Regular customer            24
31         1540  Regular customer            25
32         1540  Regular customer            27
33         1540  Regular customer            28
34         1598      New customer             1
35         1598      New customer             2
36         1598      New customer             3
37         1647      New customer             1
38         1647      New customer             4
39         1647      New customer             6
40         1647      New customer             8
41         1647      New customer             9
42         2833      New customer             1
43         2850  Regular customer             7
44         2857  Regular customer            24
45         3010  Regular customer             5
46         3029      New customer             1
47         3395      New customer             4
48         3904      New customer             1
49         4006    Loyal customer             2
50         4006    Loyal customer             3
51         4006    Loyal customer             5
52         4006    Loyal customer             9
53         4006    Loyal customer            12
54         4122  Regular customer            11
55         4141      New customer             2
56         4343      New customer             1
57         4553      New customer             3
58         4845  Regular customer             6
59         6866      New customer             1

## Step #5:  The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [48]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

### The average (i.e. mean) price for purchases by "loyal" customers is less that that for those by "regular" customers.  "New" customers had the highest average price.

## Step #6:  The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:

## If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
## If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [49]:
# Create a new column, 'avg_order', for the average price of each customer's orders.

In [50]:
ords_prods_merge['avg_order'] = ords_prods_merge.groupby(['customer_id'])['prices'].transform(np.mean)

In [51]:
# Basic sanity-checking with the 'shape' and 'head()' functions.

In [52]:
ords_prods_merge.shape

(32404859, 23)

In [53]:
ords_prods_merge.head(2)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,customer_id,order_number,orders_day_of_week,...,reordered,_merge,_merge2,price_range,price_range_loc,busiest_days,busiest_hours,max_order,loyalty_flag,avg_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,...,0,both,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,32,Regular customer,6.935811
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,...,1,both,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,32,Regular customer,6.935811

In [54]:
# Set up the 'spending_flag' column with our conditional statements.

In [55]:
ords_prods_merge.loc[ords_prods_merge['avg_order'] > 10, 'spending_flag'] = 'High spender'
ords_prods_merge.loc[ords_prods_merge['avg_order'] <= 10, 'spending_flag'] = 'Low spender'

In [56]:
# Basic sanity-checking with the 'value_counts' and 'head()' functions.

In [57]:
ords_prods_merge['spending_flag'].value_counts()

Low spender     31770995
High spender      633864
Name: spending_flag, dtype: int64

In [58]:
# We have to look beyond the first 10 results to see a 'High spender'.

In [59]:
ords_prods_merge[['customer_id', 'spending_flag', 'avg_order']].head(90).tail()

    customer_id spending_flag  avg_order
85         9694   Low spender   7.075354
86         9848   Low spender   8.312203
87        10113   Low spender   8.769565
88        10315  High spender  10.188889
89        10479   Low spender   7.779775

## Step #7:  In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:

## If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
## If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
## If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [60]:
# Create a new column, 'avg_order_frequency', for the average frequency of each customer's orders.

In [61]:
ords_prods_merge['avg_order_frequency'] = ords_prods_merge.groupby(['customer_id'])['days_since_prior_order'].transform(np.mean)

In [62]:
# Basic sanity-checking with the 'shape' and 'head()' functions.

In [63]:
ords_prods_merge.shape

(32404859, 25)

In [64]:
ords_prods_merge.head(2)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,customer_id,order_number,orders_day_of_week,...,_merge2,price_range,price_range_loc,busiest_days,busiest_hours,max_order,loyalty_flag,avg_order,spending_flag,avg_order_frequency
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,...,both,Mid-range product,Mid-range product,Regularly busy,Busiest hours,32,Regular customer,6.935811,Low spender,9.837838
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,...,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,32,Regular customer,6.935811,Low spender,9.837838

In [65]:
# Set up the 'frequency_flag' column with our conditional statements.

In [66]:
ords_prods_merge.loc[ords_prods_merge['avg_order_frequency'] > 20, 'frequency_flag'] = 'Non-frequent customer'
ords_prods_merge.loc[(ords_prods_merge['avg_order_frequency'] <= 20) & (ords_prods_merge['avg_order_frequency'] > 10), 'frequency_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['avg_order_frequency'] <= 10, 'frequency_flag'] = 'Frequent customer'
# Extra line of comments, to make selecting on the bottomm line easier in Jupyter.  Otherwise, the scroll bar is a hindrance.

In [67]:
# Basic sanity-checking with the 'value_counts' and 'head()' functions.

In [68]:
ords_prods_merge['frequency_flag'].value_counts()

Frequent customer        17747667
Regular customer         13008748
Non-frequent customer     1648444
Name: frequency_flag, dtype: int64

In [69]:
ords_prods_merge[['customer_id', 'frequency_flag', 'avg_order_frequency']].head(60)

    customer_id         frequency_flag  avg_order_frequency
0           138      Frequent customer             9.837838
1           138      Frequent customer             9.837838
2           709      Frequent customer             5.708333
3           764      Frequent customer             7.362069
4           764      Frequent customer             7.362069
5           777       Regular customer            12.176991
6           825  Non-frequent customer            20.636364
7           910      Frequent customer             7.300000
8          1052       Regular customer            10.687500
9          1052       Regular customer            10.687500
10         1379       Regular customer            15.272727
11         1480      Frequent customer             8.219388
12         1480      Frequent customer             8.219388
13         1480      Frequent customer             8.219388
14         1494      Frequent customer             5.329114
15         1494      Frequent customer             5.329114
16         1494      Frequent customer             5.329114
17         1540      Frequent customer             6.813056
18         1540      Frequent customer             6.813056
19         1540      Frequent customer             6.813056
20         1540      Frequent customer             6.813056
21         1540      Frequent customer             6.813056
22         1540      Frequent customer             6.813056
23         1540      Frequent customer             6.813056
24         1540      Frequent customer             6.813056
25         1540      Frequent customer             6.813056
26         1540      Frequent customer             6.813056
27         1540      Frequent customer             6.813056
28         1540      Frequent customer             6.813056
29         1540      Frequent customer             6.813056
30         1540      Frequent customer             6.813056
31         1540      Frequent customer             6.813056
32         1540      Frequent customer             6.813056
33         1540      Frequent customer             6.813056
34         1598      Frequent customer             5.705882
35         1598      Frequent customer             5.705882
36         1598      Frequent customer             5.705882
37         1647  Non-frequent customer            21.704225
38         1647  Non-frequent customer            21.704225
39         1647  Non-frequent customer            21.704225
40         1647  Non-frequent customer            21.704225
41         1647  Non-frequent customer            21.704225
42         2833       Regular customer            10.142857
43         2850      Frequent customer             8.720930
44         2857       Regular customer            11.806897
45         3010      Frequent customer             6.256000
46         3029  Non-frequent customer            20.393939
47         3395       Regular customer            18.925926
48         3904       Regular customer            14.000000
49         4006      Frequent customer             6.255663
50         4006      Frequent customer             6.255663
51         4006      Frequent customer             6.255663
52         4006      Frequent customer             6.255663
53         4006      Frequent customer             6.255663
54         4122      Frequent customer             8.135802
55         4141  Non-frequent customer            26.000000
56         4343       Regular customer            15.000000
57         4553  Non-frequent customer            23.421053
58         4845       Regular customer            18.555556
59         6866  Non-frequent customer            24.000000

## Step #8:  Ensure your notebook is clean and structured and that your code is well commented.

### :fingers_crosssed:

## Step #9:  Export your dataframe as a pickle file and store it correctly in your “Prepared Data” folder.

In [70]:
ords_prods_merge['prices'].max()

99999.0

In [71]:
ords_prods_merge.to_pickle(os.path.join(path, '02-Data','Prepared-Data', 'ords_prods_merge_derived_columns.pkl'))